---
- name: Install Prometheus 
  hosts: all
  become: yes

# need to change this to be idempotent.
  tasks:  
    - name: Download Prometheus
      ansible.builtin.unarchive:
        src: "{{ prometheus_url }}"
        dest: "{{ dest_dir }}"
        creates: "{{ dest_dir }}/prometheus/"
        remote_src: true
# cannot do checksum with unarchive. Change this to get_url then unarchive.

    - name: Find Prometheus directory
      ansible.builtin.find:
        paths: "{{ dest_dir }}"
        patterns: 'prometheus-*'
        file_type: directory
      register: prometheus_dir
 
    - name: print prometheus directory
      ansible.builtin.debug:
        var: prometheus_dir.files[0].path
# Might need to change perms on this file since the api key is in plain text.
    - name: Copy Prometheus configuration template
      ansible.builtin.template:
        src: prometheus.yml.j2
        dest: "{{ prometheus_dir.files[0].path }}/prometheus.yml"
        force: yes

