---
- name: Install Prometheus 
  hosts: all
  become: true

  vars_files:
    - "../vars/vars.yml"
    - "../vault/api_key.yml"

  handlers:
    - name: reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

  pre_tasks:
    - name: Create Prometheus group
      ansible.builtin.group:
        name: prometheus
        state: present

    - name: Create Prometheus user
      ansible.builtin.user:
        name: prometheus
        group: prometheus
        system: yes
        create_home: no
        shell: /sbin/nologin
        state: present

# need to change this to be idempotent.
  tasks:  
    - name: Download Prometheus
      ansible.builtin.unarchive:
        src: "{{ prometheus_url }}"
        dest: "{{ dest_dir }}"
        creates: "{{ dest_dir }}/prometheus/"
        remote_src: true
# cannot do checksum with unarchive. Change this to get_url then unarchive.
# I should just re-write this so that it uses the shell module to `mv` the directory and rename. 
    - name: Find Prometheus directory
      ansible.builtin.find:
        paths: "{{ dest_dir }}"
        patterns: 'prometheus-*'
        file_type: directory
      register: prometheus_dir
      # may need to change this to a fact so that it can be used elsewhere
      
    - name: print prometheus directory
      ansible.builtin.debug:
        var: prometheus_dir.files[0].path

# Might need to change perms on this file since the api key is in plain text.
    - name: Copy Prometheus configuration template
      ansible.builtin.template:
        src: "../templates/prometheus.yml.j2"
        dest: "{{ prometheus_dir.files[0].path }}/prometheus.yml"
        force: yes

    - name: Set ownership for Prometheus directories and files.
      ansible.builtin.file:
        path: "{{ item }}"
        owner: prometheus
        group: prometheus
        recurse: yes
      loop: 
        - "{{ prometheus_dir.files[0].path }}"  

    - name: Create Prometheus systemd service file
      ansible.builtin.template:
        src: "../templates/prometheus.service.j2"
        dest: /etc/systemd/system/prometheus.service
        owner: prometheus
        group: prometheus
        mode: 0755
      notify: reload systemd
  
    - name: Start Prometheus service
      ansible.builtin.systemd:
        name: prometheus.service  # Name of the systemd service
        state: started  # Ensure the service is started
        enabled: yes  # Ensure the service is enabled to start at boot
  
